.Dd February 22, 2025
.Dt README 7
.Os nk
.
.Sh NAME
.Nm nk
.Nd tic-tac-toe in Python
without using any keywords
.
.Sh DESCRIPTION
This is a simple game
written in Python.
It differs from others
in the abscence of keywords:
all the code is written
without using them.
.
.Pp
To play,
firstly enter
first player's side,
then enter number of cell
on every turn
according to the table below:
.TS
allbox tab(:);
c c c.
 1:2:3
 4:5:6
 7:8:9
.TE
